SELECT A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, SUM(A.T) AS TOTAL_SALES
FROM (SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, C.SALES* A.PRICE AS T
FROM BOOK A
INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
INNER JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01') A
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;
