SELECT A.CAR_ID, A.CAR_TYPE, A.FEE
FROM (SELECT DISTINCT CAR.CAR_ID, CAR.CAR_TYPE, ((CAR.DAILY_FEE - (CAR.DAILY_FEE * PLAN.DISCOUNT_RATE/100)))*30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON
CAR.CAR_ID = HISTORY.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON
CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('SUV', '세단')
AND CAR.CAR_ID NOT IN 
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') <= '2022-11-01' AND 
TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01')
AND PLAN.DURATION_TYPE = '30일 이상') A
WHERE A.FEE BETWEEN 500000 AND 2000000-1
ORDER BY A.FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;