SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX
FROM REST_INFO
GROUP BY FOOD_TYPE) A, REST_INFO B
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND
A.MAX = B.FAVORITES
ORDER BY B.FOOD_TYPE DESC;
