SELECT X.PRODUCT_ID, X.PRODUCT_NAME, X.SUM * X.PRICE AS TOTAL_SALES
FROM (SELECT A.PRODUCT_ID, A.PRODUCT_NAME,SUM(B.AMOUNT) AS SUM, A.PRICE
FROM FOOD_PRODUCT A
INNER JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE TO_CHAR(B.PRODUCE_DATE, 'yyyy-MM') = '2022-05'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE) X
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
