SELECT A.HISTORY_ID, 
((A.DAILY_FEE - (A.DAILY_FEE * NVL(A.DISCOUNT_RATE,0)/100)))*A.DAYS AS FEE
FROM (SELECT C.CAR_ID, C.DAILY_FEE, H.HISTORY_ID, H.END_DATE - H.START_DATE +1 AS DAYS , P.DURATION_TYPE, P.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = (CASE WHEN H.END_DATE - H.START_DATE +1 BETWEEN 7 AND 29 THEN '7일 이상'
WHEN H.END_DATE - H.START_DATE +1 BETWEEN 30 AND 89 THEN '30일 이상'
WHEN H.END_DATE - H.START_DATE +1 >= 90 THEN '90일 이상'
ELSE '' END)
WHERE C.CAR_TYPE = '트럭') A
ORDER BY FEE DESC, A.HISTORY_ID DESC;