-- 코드를 입력하세요
SELECT C.USER_ID, C.NICKNAME, C.SUM AS "TOTAL_SALES"
FROM (SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) AS SUM
FROM USED_GOODS_BOARD A , USED_GOODS_USER B
WHERE A.WRITER_ID = B.USER_ID AND A.STATUS = 'DONE'
GROUP BY B.USER_ID, B.NICKNAME) C
WHERE C.SUM >= 700000
ORDER BY C.SUM;